### ISSUE TITLE
update readme :)

### ISSUE THREAD

**Issue by joeblew99** [CaptainCodeman/prpl-server-go#12]
Thanks for making this, Very useful !!!

The readme example is wrong... btw

prpl.Root(...

to be:

prpl.WithRoot(...

**Comment by CaptainCodeman** [comment]
Yes, I've made some changes to make it clearer which things were options. I'll update the read-me from the example app which is deployed & working and probably the best reference.

Thank for letting me know!

**Comment by joeblew99** [comment]
sure..
This is working well for me. I run it on Mobiles, desktop and Servers.
As far as i can tell this will become redundant when they get everything converted over to Polymer 3 and ES Modules.. But not sure

**Comment by CaptainCodeman** [comment]
No, Polymer 3 will use ES Modules to load scripts instead of HTML Imports to load HTML, but the idea of using server-push instead of pre-bundling will still be applicable AFAIK.

**Comment by joeblew99** [comment]
i agree about the server push for sure.

Just not sure the polymer build file will all all be the same.
thats all.

i guess maybe we are both waiting to see if Polymer 3 and PRPL server is
supported together OR they just let everyone use webpack and rollup and
other sutff

**Comment by CaptainCodeman** [comment]
I think PRPL and http/2 server-push will still apply - it will just be JS modules being loaded instead of html imports.
